# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50, verbose_name='\u9009\u62e9')),
                ('vote', models.IntegerField(default=0, verbose_name='\u7968\u6570')),
            ],
            options={
                'verbose_name': '\u9009\u62e9',
                'verbose_name_plural': '\u9009\u62e9',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='\u95ee\u9898')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 6, 4, 22, 17, 18, 199000), verbose_name='\u95ee\u9898\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u7968',
                'verbose_name_plural': '\u6295\u7968',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
